### PR TITLE
Fix: Run build against PHP7

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds PHP 7 to the build matrix

Related to #20.

### CODE REVIEW

**Comment by thommahoney** [comment]
@localheinz I honestly don't know enough PHP to fix this test failure in PHP7 but it has to do with the argument list and the testing framework that is used in this library. If you can fix it then great, but there is no expectation for you to do so.

**Comment by localheinz** [comment]
@thommahoney 

This is related to using an outdated version of `phpspec`, I think, looking into it.

For reference, see for example https://github.com/phpspec/phpspec/issues/659.

**Comment by thommahoney** [comment]
Let's see if rebasing this over master fixes the failures on PHP 7.

**Comment by localheinz** [comment]
@thommahoney 

👍

**Pull request merged**
