### PR TITLE
Removed curl dependency and added phpspec tests

### PR DESCRIPTION
**Pull request by gonzalovilaseca**
I've reworked the whole package to remove the curl dependency. It's based on the node.js version (https://github.com/thisandagain/fastly).

The response returned by the client is in the new PSR7 standard format.

### CODE REVIEW

**Comment by gonzalovilaseca** [comment]
ping

**Comment by aspires** [comment]
@fastly/api is anyone able to review?

**Comment by gonzalovilaseca** [comment]
ping

**Comment by vvuksan** [comment]
Hi Gonzalo, 

Your request is being reviewed. Sorry for the delay in responding.

**Comment by gonzalovilaseca** [comment]
ping!

**Comment by alieander** [comment]
Hey @gonzalovilaseca,

First, sorry that it took so long to get someone to take a look at this...
Thank you for taking time to make these changes and to write the tests to back them up.

While php is not my strong suit, I do not see an issue with this PR. You are taking knowledge of much of the API out of the client here and leaving it up to the user to discover what they need via the documentation. This will make this client much easier to update and maintain in the future.

I will attempt to resolve the merge conflicts here and get this on master.
This will be tagged as v0.2.0

**Comment by alieander** [comment]
Bah!
I screwed that up a bit... The code is now on master but I am just going to close this PR...
Hope thats works.Thanks!

**Pull request closed without merging**
