### PR TITLE
Composer compatibility for easier installation and usage

### PR DESCRIPTION
**Pull request by LarsFronius**
* Adds composer.json
 * Clarifies README
 * Adds Fastly namespace
 * renames fastly_api.php

Maybe you guys want to register the library at https://packagist.org as well.

### CODE REVIEW

**Comment by InvertedAcceleration** [comment]
We would also be keen on having composer & packagist support.  It really is the standard way to allow PHP devs to use this wrapper.

**Comment by codeslaw** [comment]
Thirded.

**Comment by pnu** [comment]
:+1:

**Comment by snellingio** [comment]
:+1: Please!

**Comment by alieander** [comment]
I rebased this branch over master and opened #6 to replace this. Thanks @LarsFronius

**Comment by alieander** [comment]
Merged #6 
Registered this with https://packagist.org  as well.

**Pull request closed without merging**
